### ISSUE TITLE
panic error

### ISSUE THREAD

**Issue by foobargeez** [esimov/pigo#11]
```
$> ./pigo -in input.jpg -out output.jpg -cf data/facefinder
Processing... -panic: runtime error: index out of range

goroutine 1 [running]:
github.com/esimov/pigo/core.(*Pigo).Unpack(0xc4206a8d50, 0xc420672000, 0x0, 0x200, 0x200, 0x0, 0x0)
        /home/esimov/Projects/Go/src/github.com/esimov/pigo/core/pigo.go:66 +0xc5e
main.(*faceDetector).detectFaces(0xc4206a8f40, 0x7ffe8b90d545, 0x2d, 0x3, 0x3, 0x1, 0x50a920, 0xc42007e0c0)
        /home/esimov/Projects/Go/src/github.com/esimov/pigo/cmd/pigo/main.go:164 +0x23b
main.main()
        /home/esimov/Projects/Go/src/github.com/esimov/pigo/cmd/pigo/main.go:95 +0x296
```

pigo v1.1.0

What am I missing?

**Comment by foobargeez** [comment]
I just `touch`ed data/facefinder -- not sure if pigo expects something in it.

**Comment by foobargeez** [comment]
never mind .. I downloaded the binary and didn't clone the repo which is where data/facefinder is.  Can the error be more descriptive/helpful?

**Comment by esimov** [comment]
How did you downloaded? I'm afraid the binary file you have used is corrupted.
